### ISSUE TITLE
Krigga testing

### ISSUE THREAD

**Issue by xtonwallet** [tact-lang/tact-vscode#1]
From https://github.com/ton-society/ton-footsteps/issues/131#issuecomment-1523753123

While evaluating this extension, I found a few issues:

* Autocomplete does not seem to work for some standard functions. For example, autocomplete suggests beginCell, but then fails to suggest endCell, beginParse, loadAddress or loadInt.
* I could not get any kind of refactoring to work, not even renaming of variables or functions
* Errors are highlighted correctly, but the detailed error description that pops up when hovering the cursor over the error contains a lot of junk, such as the source file path, line and column, and source snippet, like so:
```
/path/to/dir/test.tact:1:1: Trait A not found
Line 1, col 1:
> 1 | contract Test with A {
      ^~~~~~~~~~~~~~~~~~~~~~~~
  2 |     init () {
```

Of all this, only Trait A not found should be in the detailed error description

**Comment by logvik** [comment]
By items:
1. Here was found some issues related to not covered by the autocomplete feature init/onbounce/receive function types. It has been fixed in the last release.
2. This was added with the last release. Please, suggest which additional actions could be useful. For now, only rename/dump actions were introduced.
3. This output goes directly from Tact compiler. I assume that we can't change it, because as only @ex3ndr will change this output, this extension will be broken. @ex3ndr please advise how to resolve it...

@krigga

**Comment by krigga** [comment]
By items:
1. The functions that I listed still were not suggested in autocomplete.
2. Rename works, but it seems that it just replaces the whole string in the whole file, which is not how renaming should work. For example, if I have a message `Test` with a field `amount` and then I have a variable `amount1` not related to that field, that will get renamed during refactoring too. The dump action works in a weird way too, seems to just insert the `dump()` string on the spot.
3. I suppose this cannot be fixed without some tact compiler support, and it's also not as important, so this can be ignored.

**Comment by logvik** [comment]
1. To the latest version has added the cascade call style.
![autocomplete_cascade](https://github.com/tact-lang/tact-vscode/assets/2010097/77723aeb-8d29-42b0-bc17-4c7fff614a23)
3. The issue with `rename` feature has been fixed. The code action for `dump` command works by the new logic.
![dump](https://github.com/tact-lang/tact-vscode/assets/2010097/c544e4f4-a7f8-455b-b1a4-ae8b97b71e7f)

**Comment by krigga** [comment]
Looks good! The issue can be closed

**Comment by logvik** [comment]
Thank you for this contribution!
