### ISSUE TITLE
Error of relative import path

### ISSUE THREAD

**Issue by alan890104** [tact-lang/tact-vscode#13]
First of all, thank you very much for creating such a useful VSCode plugin for tact developers! However, we, at Ton Dynasty, have recently encountered some issues regarding relative import paths while using this plugin.

[This](https://github.com/Ton-Dynasty/tondynasty-contracts/blob/main/contracts/nft_enforce_royalty_example.tact) is one of the file which will cause error:  

![image](https://github.com/tact-lang/tact-vscode/assets/48343225/11b53302-2ff2-4936-afd9-a0ec8eedf722)

The error says:
> Could not resolve import ./packages/token/nft/NFTCollection in /home/alankingdom/文件/ton-dynasty/contracts/contracts/nft_enforce_royalty_example.tact

Our contract refers to the contents of `packages/token/nft/NFTCollection`, but as you can see in the image, due to the inability to resolve relative paths successfully, this plugin's other features are also affected.

**Comment by alan890104** [comment]
I have just updated the link to our contract. I paste it here as well to help you investigate the error.

https://github.com/Ton-Dynasty/tondynasty-contracts/blob/main/contracts/nft_enforce_royalty_example.tact

**Comment by logvik** [comment]
please use the relative path with extension `.tact`. It is required, because you can also import with `.func` extension, for example, and then we must to know which handler to use such file type.
