### ISSUE TITLE
When I migrate to this extension in Tact, it will got error when I save the file.

### ISSUE THREAD

**Issue by howardpen9** [tact-lang/tact-vscode#18]
<img width="817" alt="image" src="https://github.com/tact-lang/tact-vscode/assets/36764495/c91b829f-a215-42bf-9a88-b1af7daec02a">

https://www.loom.com/share/7b8f72198fe84a139ee120374047dfc1

**Comment by logvik** [comment]
Does this problem appear after the formatting or how?

**Comment by howardpen9** [comment]
After the formatting. (aka. Ctrl + F)

**Comment by logvik** [comment]
Fixed on v1.0.10
