### ISSUE TITLE
Got the wired suggest in Tact code in codeblock.

### ISSUE THREAD

**Issue by howardpen9** [tact-lang/tact-vscode#19]
<img width="1023" alt="image" src="https://github.com/tact-lang/tact-vscode/assets/36764495/6b1d2158-62f2-42a3-b885-f9f7e0031592">

Shows as this, when I coding in Tact it will suggest out of aspect suggestion in Tact code.

**Comment by logvik** [comment]
What do you mean exactly? What do you offer to change? The methods are available with the right parameters - https://docs.tact-lang.org/language/ref/common#contractaddress
Please, specify more information or explain offered modifications in this behaviour.

**Comment by logvik** [comment]
No information was added. Please, reopen it with an certain offer if this issue is still actual. Thank you.
