### ISSUE TITLE
When a line of code is commented out, it still retains its color in our VS Code.

### ISSUE THREAD

**Issue by howardpen9** [tact-lang/tact-vscode#20]
<img width="1094" alt="image" src="https://github.com/tact-lang/tact-vscode/assets/36764495/cc17dae3-6373-4b63-8b48-7ddf5a7c8739">

Hi, in Tact-lang, we can commented the line of code using "//" or "/* ....... */". In this case we need optimize the readability there I think. Thank you.

**Comment by logvik** [comment]
<img width="612" alt="2023-11-22 17_17_04- Extension Development Host  ● nft_example tact - tondynasty-contracts - Visual " src="https://github.com/tact-lang/tact-vscode/assets/2010097/05a9dad0-400e-4b10-9e10-bfb940b79998">

I can't confirm it, maybe some issue with your local color scheme, if no, please reopen and attach more information. Thank you.
