### ISSUE TITLE
`textDocument/formatting` is not supported

### ISSUE THREAD

**Issue by novusnota** [tact-lang/tact-vscode#29]
Language server as per LSP documentation can support [textDocument/formatting](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_formatting) method, which is called in any LS clients (mainly in editors) whenever whole file formatting is needed.

At the moment, this plugin has formatting implemented as a VSCode-only feature and not a part of LSP specification, which results in failure to format Tact code when the language server of this plugin is used independently (i.e. [here](https://github.com/ton-society/grants-and-bounties/issues/352)) — a message such as this is shown: `"textDocument/formatting not supported for tact"`.

The solution would be to register [formatting capabilities](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_formatting) and handle the `textDocument/formatting` request.

Additionally, there are two similar methods specified in LSP, which may also be handled to further improve UX:
* [textDocument/rangeFormatting](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_rangeFormatting)
* [textDocument/onTypeFormatting](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_onTypeFormatting)

**Comment by logvik** [comment]
I assume that this part can be done within `grants-and-bounties` task. PR is welcome.

**Comment by novusnota** [comment]
@logvik Good suggestion, will do!

UPD: Tried to do it, with no avail yet.

**Comment by logvik** [comment]
Resolved at #38
