### ISSUE TITLE
Support Tact v1.3.0 release

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact-vscode#32]
The Tact team has just release Tact v1.3.0 on NPM.

The full CHANGELOG for Tact v1.3.0 can be found here: https://github.com/tact-lang/tact/blob/main/CHANGELOG.md#130---2024-05-03

And here are a summary of editor/IDE-relevant Tact features.

### New or fixed syntax
- [x] Fixed precedence levels for bitwise operators, equality and comparisons. Now the precedence levels match common languages like JS/TS.
- [x] Support for string escape sequences: `\\`, `\"`, `\n`, `\r`, `\t`, `\v`, `\b`, `\f`, `\u{0}` through `\u{FFFFFF}`, `\u0000` through `\uFFFF`, `\x00` through `\xFF`.
- [x] Allow chaining method calls with `!!`, for instance, `map.asCell()!!.hash()` is grammatically correct now.
- [x] Trailing commas are allowed in struct instantiations, `initOf` arguments, `init()` parameters, inherited traits via `with`, function arguments and parameters.
- [x] Struct fields punning, i.e. `{foo, bar}` is syntactic sugar for `{ foo: foo, bar: bar }`.
- [x] Inherited trait lists now must be non-empty if `with` is used.
- [x] Bitwise XOR (`^`) operator.
- [x] The implicit empty `init` function is now present by default in the contract if not declared.
- [x] `try {...}` and `try {...} catch {...}` statements.
- [x] `foreach` loop for the `Map` type: `foreach (k, v in map) {...}`.

### New stdlib functions

- [x] `pow2`, `log2` and `log` math functions in `@stdlib/math`.
- [x] Reserve mode constants in `@stdlib/reserve`, namely `ReserveExact`, `ReserveAllExcept`, `ReserveAtMost`, `ReserveAddOriginalBalance`, `ReserveInvertSign`, `ReserveBounceIfActionFail`.

### New methods

- [x] The `concat` non-modifying `StringBuilder`'s extension function for chained string concatenations: `foo.concat(bar).concat(baz)`.
- [x] The `toString` extension function for `Address` type: `addr.toString`.
- [x] The `isEmpty` and `del` extension functions for the `Map` type: `map.isEmpty`, `map.del(key)`.

**Comment by novusnota** [comment]
This seems to be completed in https://github.com/tact-lang/tact-vscode/commit/92f56a95f22bdfd3fa3f84f5a1453036a5c23690, at least in terms of syntax.

The new version of the extension is out on the marketplace and I've updated the [extracted language server](https://www.npmjs.com/package/tact-extracted-ls) too :)
