### ISSUE TITLE
Bug: only syntax highlight is working

### ISSUE THREAD

**Issue by NarHakobyan** [tact-lang/tact-vscode#33]
On the extension page, it has a lot of other features like, autocomplete, info on hover, etc. but in my case, it's just highlighting
Autocomplete works partially

<img width="463" alt="image" src="https://github.com/tact-lang/tact-vscode/assets/1781506/3b41c8bf-2e4a-4c07-9612-3ea0541b7701">

https://github.com/tact-lang/tact-vscode/assets/1781506/d7465047-4ff7-4d2b-9e8e-37d9ab6e7193

**Comment by logvik** [comment]
Thank you for your comment. Please, specify all cases that you have found and they must to be fixed. Just because there exists many cases that didn't covered by tests yet. For example, from the video above I have noticed only that autocomplete didn't show "address" in the list.  Something yet?

**Comment by NarHakobyan** [comment]
> Thank you for your comment. Please, specify all cases that you have found and they must to be fixed. Just because there exists many cases that didn't covered by tests yet. For example, from the video above I have noticed only that autocomplete didn't show "address" in the list. Something yet?

Hi @logvik, There are too many :/

these functions are not exists during the autocomplete
self.reply(), sender(), address(), now() shows as type, send(), ...

info on hover doesn't work at all

**Comment by logvik** [comment]
> info on hover doesn't work at all

https://github.com/tact-lang/tact-vscode/blob/main/src/hoverService.ts#L110 - at the moment only these function support info on "hover", but all improves continually.

Other issues with autocomplete will be fixed at the next release.

**Comment by logvik** [comment]
Added autocomplete for global messages/structs. I will continue the adding of improvements time by time.
