### ISSUE TITLE
Support Tact 1.4.0

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact-vscode#36]
The following is the list of IDE-relevant changes for Tact v1.4.0 which has been released. The full changelog is here: https://github.com/tact-lang/tact/blob/main/CHANGELOG.md#140---2024-06-21.
### New or changed syntax

- [ ] Unary bitwise NOT operation: `~`.
- [ ] Augmented assignment bitwise operators: `|=`, `&=`, `^=`.
- [ ] `foreach` loop for the `Map` type now works not only with simple identifiers, but with contract storage and struct fields too: `foreach (k, v in self.map) {...}` or `foreach (k, v in struct.map) {...}`.
- [ ] Trailing semicolons in struct/message declarations are optional now: `struct Foo {x: Int}` is valid syntax now.
- [ ] Trailing semicolon in for the last statement in a block is optional now: `{ let x: Int = 42 }` is valid syntax now.
- [ ] Type annotation for `let`-statements are optional now: `let x = 42` is valid syntax now.

### stdlib functions

- [ ] Fixed the return type of `skipBits` in stdlib/std/cells.tact: `extends mutates native skipBits(self: Slice, l: Int)` (used to return `Int`, now it's `void`).
- [ ] New `loadBool` method for slices.
- [ ] New `fromCell` and `fromSlice` methods for struct parsing.
- [ ] `nativeThrowWhen` has been renamed to `nativeThrowIf`.

**Comment by anton-trunov** [comment]
Tact v1.4.0 has just been released, looking forward to see it supported in VS Code!

**Comment by logvik** [comment]
> Tact v1.4.0 has just been released, looking forward to see it supported in VS Code!

ok, I will start next week already

**Comment by anton-trunov** [comment]
Btw, in terms of Marketplace publishing, we should target Tact v1.4.1 bugfix release, which is going to be release early next week.

**Comment by logvik** [comment]
Added v1.4.0, I will wait for v1.4.1

**Comment by anton-trunov** [comment]
> Added v1.4.0, I will wait for v1.4.1

We just released 1.4.1 -- https://www.npmjs.com/package/@tact-lang/compiler/v/1.4.1

**Comment by logvik** [comment]
The new version for v1.4.1 has been published on the marketplace.

**Comment by anton-trunov** [comment]
Awesome! Thanks so much. I'll open a separate issue to support Tact v1.4.2 which accumulates lots and lots of bug fixes
