### ISSUE TITLE
Bug: internal prettier removes `?`

### ISSUE THREAD

**Issue by midas-myth** [tact-lang/tact-vscode#37]
Hello, thank you for this extension.

Possibly related to #34

The following code will break if comment is removed. It seems prettier removes `?`
```tact
    receive(msg: AcceptInvite){
        // prettier-ignore
        let invite: Bool? = self.invites.get(sender());
    }
```

**Comment by logvik** [comment]
Hi, yes, this issue is related to the formatting feature. I hope, that it will be fixed during a week, sorry for the delay, too busy right now.
