### ISSUE TITLE
Incorrect diagnostics: `Unsupported format remaining for map value`

### ISSUE THREAD

**Issue by novusnota** [tact-lang/tact-vscode#41]
Tact compiler allows specifying `remaining` as a serialization format for map values, despite that it doesn't actually do anything and default still applies. Consider the following example:

```tact
contract Example {
    m: map<Int, Cell as remaining>; // ← compiles fine,
                                    // albeit as `dict<uint8, ^cell>`, and not
                                    // `dict<uint8, remainder<cell>>` as one might expect
}
```

However, tact-vscode considers it an error, showing `Unsupported format remaining for map value`, while the code compiles just fine under Tact v1.4.0 and newest dev versions, see: https://github.com/tact-lang/tact/issues/569#issuecomment-2247221601

**Comment by logvik** [comment]
I am waiting for https://github.com/tact-lang/tact-vscode/issues/36, fixes are not at marketplace yet
