### ISSUE TITLE
Support Tact 1.4.4 when it lands on NPM

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact-vscode#42]

**Comment by anton-trunov** [comment]
@logvik Tact v1.4.2 bugfix release just landed on NPM. Can you please update the plugin to use it?

**Comment by anton-trunov** [comment]
Actually, let's update to Tact v1.4.3. @logvik do you have a timeline in mind?

UPD: Tact v1.4.4 has been released

**Comment by logvik** [comment]
I hope it will be published by the end of this week

**Comment by logvik** [comment]
Published today

**Comment by anton-trunov** [comment]
Awesome! Thanks a lot!
