### ISSUE TITLE
SHA256 showing error, but compiles ok

### ISSUE THREAD

**Issue by bulba03** [tact-lang/tact-vscode#7]
Using sha256() showing as error in editor, but if you'll compile the code, FUNC code generates great and have no compile errors.

[{
	"message": "/workspace/proj-name/contracts/contract.tact:129:42: Static function \"sha256\" does not exist
}]

Code: 
let A: Int = sha256("abcd");

**Comment by logvik** [comment]
fixed on version 1.0.3
